language: python
python:
#  - "3.3"
  - "2.7"
#  - "2.6"
addons:
  apt_packages:
    - pandoc
install:
- npm install -g grunt-cli
- pip install -r requirements_dev.txt
- ./fine-uploader-build.sh $FINE_UPLOADER_VERSION
script:
- drf_to_s3/runtests/runtests.py
- drf_to_s3/runtests/runtests.py integration
env:
  global:
  - FINE_UPLOADER_VERSION=5.0.7
  - secure: N+bw+xdt1r9p9ePkNoUkTluhT2T7TZeN/NletFPUps/bubO8o0tAifLPwqHSoBIh4N4ms4heNHf/nH7lV+8V5VQVaU/rdTfKc8CJW3OB7wmt/ZDU9Gry8RYFvxvfWCib0WHBxh9tvGacJ+t+Yd5eevpRTYZHS4OoGmmRi098PNE=
  - secure: E7iOE8Oo8PmqE8hPHKfS+vL41Cl+1EZZrz4MtXRZtpv3r8wBvcKnAJrTELBUXROFuwZBFIb5OLNMQzq1kfbPWZRXDbiphCpJfTut85c0l4gJQ8U85XTwi7pXtkAxG5bsqMa1vUqdEqPFEi+e0T4o2w7Z4wLuvokJgygrb5uJdBg=
addons:
  sauce_connect:
    username: paulmelnikow
    access_key:
      secure: bQb/lrZ5I7kIwM+wrTBiZHUIsVe1StCzzfp14XBffEYIOWnpPz+YukTtgeIlf73UaakN4GLDsHcX8BEBpDdFvaMcvQvjbFWAD1y9ZGVX/Rikxn+9BdkVaanpvtmURJ6IA2a8/cLttt92JzAQabJxqBWTbDcU6dG5xUrk1kPGMdk=
notifications:
  hipchat:
    rooms:
      secure: B3Xe8WuUXOdoxUTHsoLe5t6zbeCZsBkS+YHfi69BXapDsO2V/cZvQC/u5eSx4KXxy6VDmLMDMS7VILB0cS3/AULdWAMTXju/q/C7y/h2dVHKD0YeIiOTn47bg0pxDOprdzZbc3J80u31S+zDqbjH7d+GnTavetJ2f8Wh3HrdSBg=
